version: 2
jobs:
  build:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      - run: npm ci && npm run test
